name: Deploy Thesauri PoolParty

on:
  workflow_dispatch:  # Handmatige trigger
  schedule:           # Periodieke trigger (optioneel)
    - cron: "0 3 * * *"  # Elke dag om 03:00 UTC

jobs:
  deploy:
    runs-on: windows-latest  # Gebruik alleen Windows

    steps:
    # 1. Haal de code op uit de repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Installeer Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"  # Gebruik de gewenste Python-versie

    # 3. Installeer vereiste Python-pakketten
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Download de TriplyDB CLI
    - name: Download TriplyDB CLI
      run: |
        Invoke-WebRequest -Uri https://static.triply.cc/cli/triplydb.exe -OutFile triplydb.exe

    # 5. Voer het Python-script uit met omgevingsvariabelen
    - name: Run thesauri-poolparty script
      run: |
        python thesauri-poolparty.py
      env:
        POOLPARTY_AUTH: ${{ secrets.POOLPARTY_AUTH }}
        TRIPLYDB_TOKEN: ${{ secrets.TRIPLYDB_TOKEN }}
